services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWERCASE}/trinity-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env # load credentials from your .env on EC2
    environment:
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    restart: always
